import Link from 'next/link';
import {Suspense} from 'react';
import {Portrait,BookCard,TextLink,Atlas} from '@/components/ui';
import Writing from '@/components/writing';
import {projects,site} from '@/lib/content';
export const revalidate=3600;
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><span className="eyebrow">Author · Technologist · Social entrepreneur</span><h1>A life of ideas.<br/><em>Put into practice.</em></h1><p>I write books, build ventures, and explore history through stories and data. My work focuses on expanding educational opportunity and helping people find connection, particularly those living with rare diseases.</p><div className="actions"><a className="button" href="#selected">Explore my work <span aria-hidden="true">↓</span></a><Link className="quiet-link" href="/about">About me</Link></div></div><figure><Portrait/><figcaption>Paolo Narciso <span>Author & founder</span></figcaption></figure></section>
<section id="selected" className="section"><div className="section-heading"><div><span className="eyebrow">01 / Writing & building</span><h2>Selected work</h2></div><p>Ideas on the page.<br/>Opportunity in the world.</p></div><div className="selected-grid"><BookCard index={0}/><article className="project-card core"><span className="eyebrow">Founder / Educational opportunity</span><div><span className="project-name">Core Immersive</span><h3>{projects[0].title}</h3><p>{projects[0].description}</p></div><TextLink href="/social-impact#core-immersive">Explore Core Immersive</TextLink></article><BookCard index={1}/><article className="project-card goaxi"><span className="eyebrow">Founder / Rare disease & connection</span><div><span className="project-name">GoAxi</span><h3>{projects[1].title}</h3><p>{projects[1].description}</p></div><TextLink href="/social-impact#goaxi">Discover GoAxi</TextLink></article></div><div className="section-end"><TextLink href="/books">Browse all books</TextLink><TextLink href="/social-impact">More about my social impact work</TextLink></div></section>
<section className="section"><div className="section-heading"><div><span className="eyebrow">02 / Notes & perspectives</span><h2>Latest writing</h2></div><TextLink href={site.substack}>Read on Substack</TextLink></div><Suspense fallback={<p>Essays and reflections, published on Substack.</p>}><Writing/></Suspense><div className="section-end"><p>Essays and reflections, published on Substack.</p><TextLink href={`${site.substack}/subscribe`}>Subscribe on Substack</TextLink></div></section>
<section className="section"><div className="section-heading"><div><span className="eyebrow">03 / Following curiosity</span><h2>Explorations</h2></div><p>History and human stories,<br/>through data and film.</p></div><div className="explore-grid"><Atlas/><article className="history-panel"><span className="eyebrow">Short films / Philippine history</span><h3>Small stories.<br/>A deeper history.</h3><p>Mini Philippine History Lessons explores people and events in Philippine history through short videos.</p><ul><li>The First Filipinos in America: Morro Bay 1587</li><li>The End of Spanish Rule in the Philippines</li><li>Lapu Lapu: The First Filipino Hero</li></ul><TextLink href={site.youtube}>Watch on YouTube</TextLink></article></div></section>
<section className="connection"><span className="eyebrow">A commitment to connection</span><h2>Opportunity grows.<br/><em>Connection matters.</em></h2><p>Alongside my work as a founder, I serve on the boards of the Foundation for Social Connection and CaringBridge. Educational opportunity, social connection, and loneliness are central concerns in the work I choose to do.</p><TextLink href="/about">More about my work and background</TextLink></section>
</>}
